import type { Metadata } from "next";
import {
  CONTACT_EMAIL,
  LegalPage,
  LegalSection,
  legalStyles as styles,
} from "@/features/onboarding/legal-page";

export const metadata: Metadata = {
  title: "Terms",
  description: "The terms that govern use of the H3 Max Realtime Education science companion.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use" updated="August 2026">
      <LegalSection heading="The service">
        <p className={styles.legalBody}>
          H3 Max Realtime Education is a conversational science companion for learners aged 13–18. It provides
          live tutoring, generated visualizations, and mastery tracking for educational
          purposes.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <ul className={styles.legalList}>
          <li>Use H3 Max Realtime Education for learning, teaching, and exploration.</li>
          <li>Do not attempt to disrupt the service or access other learners&apos; sessions.</li>
          <li>Do not use H3 Max Realtime Education to generate harmful, harassing, or unlawful content.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Educational content">
        <p className={styles.legalBody}>
          Lessons are generated by an AI tutor and reviewed against a safety and pedagogy
          contract, but they are not a substitute for a qualified teacher. Always verify
          important results against your curriculum materials.
        </p>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <p className={styles.legalBody}>
          We may update these terms as the product evolves; material changes will be noted on
          this page. Questions about these terms:{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
